### ISSUE TITLE
Дополнительные опции

### ISSUE THREAD

**Issue by khusamov** [safronizator/damnUploader#10]
Здравствуйте! Спасибо за плагин!

Не хватает опций:

method: POST || PUT
Чтобы было совместимо с протоколом RESTfull.

params: {}
Помимо имени файла на сервер нужно передавать дополнительные параметры. Опять-таки, это косвенно связано с RESTfull.

Не хватает плагина не для jQuery, а для Ext JS 4.x.x.

**Comment by sectus** [comment]
Поддерживаю идею о возможности добавлять дополнительные параметры. Приходится возиться со строками.

**Comment by webproducer** [comment]
Про POST || PUT - принято.

Что касается параметров, то их можно привязывать к каждому загружаемому файлу отдельно. Пример:
```javascript
$fileInput.on('du.add', function(e) {
    console.log('File added: ' + e.uploadItem.file.name);
    e.uploadItem.addPostData({ hello: "world" });
});
```

**Comment by sectus** [comment]
@webproducer , о, не нашёл этого в документации.

**Comment by safronizator** [comment]
С дополнительными параметрами сразу разобрались (плюс немного подновил документацию)

А возможность выбора HTTP-метода добавил. Пример использования теперь есть в демке.

**Comment by safronizator** [comment]
P.S. C Ext JS, к сожалению, не знаком
