### ISSUE TITLE
Метод cancel

### ISSUE THREAD

**Issue by ilie20088** [safronizator/damnUploader#24]
Добрый день, скажите пожалуйста. Если я делаю вот так вот, должны элементы удалятся из очереди?
$i.on('du.add', function(a) {
      a.uploadItem.cancel();
  });

Они почему-то у меня не удаляются.

**Comment by ilie20088** [comment]
Я пытаюсь решить проблему безграничного количества отправки файлов.
Лимит работает только для одного вызова ( я автоматически отправляю ). Но можно несколько раз выбирать файлы и они будут отправляться.

**Comment by safronizator** [comment]
Это делается также, как в случае со "стандартными" событиями:
```javascript
$i.on('du.add', function(a) {
  a.preventDefault();
});
```
