### ISSUE TITLE
Типы загружаемых файлов

### ISSUE THREAD

**Issue by mrdubz** [safronizator/damnUploader#25]
Привет!
Все хорошо, но хотелось бы ограничивать типы загружаемых файлов, например, только изображения (указывать определенные форматы).

**Comment by safronizator** [comment]
Годное предложение, я рассмотрю, спасибо.

Если речь идет только о том, чтобы запретить выбирать неправильные форматы, то можно добавить проверку в обработчик события добавления:
```javascript
$fileInput.on('du.add', function(e) {
  if (!isCorrectType(e.uploadItem.file.type)) {
    notifyUser('File with incorrect type selected');
    e.preventDefault();
    return;
  }
  // handle correct files adding or just do nothing
});
```

**Comment by safronizator** [comment]
... более того, это единственный способ ограничения в случае выбора файлов через Drag&Drop (другое дело, что можно попытаться немного облегчить этот процесс в рамках плагина).

Для того чтобы ограничить тип выбираемых файлов в стандартном диалоге, попробуйте использовать [атрибут accept](http://www.w3schools.com/tags/att_input_accept.asp) для тега `<input/>`

**Comment by scofield-ua** [comment]
А в чем проблема? Я, например, без проблем загружал pdf\doc\txt файлы

**Comment by safronizator** [comment]
Добавил возможность указания типов файлов. Но проверка самая базовая, поэтому на сервере все равно необходимо перепроверять. Пример использования:
```javascript
$fileField.damnUploader({
    acceptType: 'image/*' // all types of images is accepted
    // ...
});
```
