### ISSUE TITLE
duStart VS upload

### ISSUE THREAD

**Issue by ugputu** [safronizator/damnUploader#27]
Хочу сделать чтобы при добавлении файлов они автоматом закачивались, и потом вызывался completed но при использовании ui.upload() этот колбек не вызывается, а работает он только если делать duStart на отдельную кнопку.

Где перехватить окончание добавления файлов в очередь, чтобы вызвать duStart?

**Comment by safronizator** [comment]
Ну как один из вариантов, можно так:
```javascript
var addTimeoutId;
var startUploads = function() {
	$fileInput.duStart();
};
$fileInput.on({
    'du.add' : function() {
    	addTimeoutId && clearTimeout(addTimeoutId);
    	addTimeoutId = setTimeout(startUploads, 500);
    },
    'du.completed' : function() {
        console.log("All uploads completed!");
    }
});
```

**Comment by ugputu** [comment]
Я сделал подругому, немного поломал основной скрипт.

Добавил в сеттинг stopOnLimit
Добавил в if (isFileField) { и в if (set.dropping) { проверку на превышение лимита если stopOnLimit == true тогда вызываем колбек который говорит что не больше Х файлов.

И по основному вопросу, по поводу вызова комплита, я еще не решил, но думаю буду считать файлы которые загрузились, отнимать из общей очереди. Думал про таймаут, но решил отказаться.
