### ISSUE TITLE
Некорректно отрабатывает multiple: false 

### ISSUE THREAD

**Issue by shulya** [safronizator/damnUploader#28]
Если указать  multiple: false , то возникает ошибка в случае попытки повторной загрузки одиночного файла потому что срабатывает условие:
            if ($this._duItemsCount === set.limit) {
                $this.trigger(limitEvent);
                return false;
            }

Соответственно  гасится возможность повторного аплоада одиночного файла.
Пофиксил у себя так:
if (set.limit > 1 && $this._duItemsCount === set.limit) {

**Comment by safronizator** [comment]
Спс за репорт. Оформите пулл-реквест?

**Comment by safronizator** [comment]
Не удалось воспроизвести описанный баг: ставлю в демке параметры `{multiple: false, limit: 1}` - и все работает как и должно. Так что тут либо что-то настроено не верно у Вас, либо необходимо точнее описать кейс.
