### ISSUE TITLE
Кнопка "Удалить"

### ISSUE THREAD

**Issue by Tuning-Soft** [safronizator/damnUploader#31]
Отличный плагин, еще вот не хватает кнопки "Удалить", которая не просто в html удаляет верстку, но и сам файл с сервера, будет супер!

**Comment by safronizator** [comment]
Спс за отзыв!

Дело в том, что такая кнопка сильно зависела бы от серверной части (ведь заранее неизвестно, как именно реализован API удаления файлов на сервере). С другой стороны, не должно возникать особых сложностей с тем, чтобы навесить аякс-запрос на кнопку удаления в интерфейсе.
